# Application
server:
  port: 18080

## Dubbo
dubbo:
  application:
    name: ddo-web
  registry:
    protocol: zookeeper
    address: 192.168.74.128:2181,192.168.74.129:2181,192.168.74.130:2181,192.168.74.131:2181
#  scan: cn.bounter

# thymeleaf
  spring:
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML
      encoding: UTF-8
      content-type: text/html
      cache: false  # 开发阶段务必关闭缓存 (=false)

